version: '3.0'

expectations:
  population_size: 10000

actions:
  # for creating multiple cohorts where the only difference is the index date, then have multiple actions in the yaml, one for each index date
  # the range is specified as: --index-date-range "YYYY-MM-DD to YYYY-MM-DD by (week|month)" 
  # as files are large, use csv.gz to make them smaller

  generate_study_population:
    run: cohortextractor: generate_cohort --study-definition study_definition --index-date-range "2018-01-01 to 2022-01-01 by month" --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input-YYYY-MM-DD.csv.gz

calculate_measures:
    run: cohortextractor:latest  generate_measures --study-definition study_definition --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_YYYY-MM-DD.csv