version: '3.0'

expectations:
  population_size: 1000

actions:
  # Study population for lone households and mental health outcomes
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2018-03-01 to 2022-01-01 by month" --output-dir=output/measures --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv
  # Relative outcome measures
  calculate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_*.csv
  # Model checks for normality, seasonal effects, lags, etc.
  check:
    run: stata-mp:latest analysis/modelcheck.do
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        log: output/modelcheck.txt
        figures: output/tabfig/checks_*.svg
  # Model coefficients from time series analysis     
  describe:
    run: stata-mp:latest analysis/timeseries.do
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        log: output/tsreg.txt
        tables: output/tabfig/tsreg_tables*.csv
  # Line graphs
  graph:
    run: stata-mp:latest analysis/lines.do
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        log: output/lines.txt
        results: output/tabfig/lines_*.svg
      