version: '3.0'

expectations:
  population_size: 1000

actions:
  # Study population for lone households and mental health outcomes
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2018-03-01 to 2022-01-01 by month" --output-dir=output/measures --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv
  # Relative outcome measures
  calculate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_*.csv
  # Model checks for normality, seasonal effects, lags, etc.
  check:
    run: stata-mp:latest analysis/modelcheck.do
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        log: output/modelcheck.txt
        figures: output/tabfig/checks_*.svg
  # Model coefficients from time series analysis     
  describe:
    run: stata-mp:latest analysis/timeseries.do
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        log: output/tsreg.txt
        tables: output/tabfig/tsreg_tables*.csv
        figures: output/tabfig/margin_*.svg
  # Line graphs
  graph:
    run: stata-mp:latest analysis/lines.do
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        log: output/lines.txt
        results: output/tabfig/lines_*.svg
  # Sensitivity analysis     
  sensitivity:
    run: stata-mp:latest analysis/sensitivity.do
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        log: output/sensitivity.txt
        tables: output/tabfig/sens_tables*.csv
        figures: output/tabfig/sens_mar_*.svg
        results: output/tabfig/senslin_*.svg
  # Generates study populations for baseline tables at 3 timepoints
  generate_study_population_tables_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_tables --index-date-range "2019-01-01" --output-dir=output/measures/tables --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/tables/input_tables_2019-01-01.csv
  generate_study_population_tables_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_tables --index-date-range "2020-01-01" --output-dir=output/measures/tables --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/tables/input_tables_2020-01-01.csv
  generate_study_population_tables_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_tables --index-date-range "2021-01-01" --output-dir=output/measures/tables --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/tables/input_tables_2021-01-01.csv  
  # Baseline tables
  create_baseline_tables:
    run: stata-mp:latest analysis/baseline_tables.do  
    needs: [generate_study_population_tables_2019, generate_study_population_tables_2020, generate_study_population_tables_2021]  
    outputs:
      moderately_sensitive:
        log: logs/table1_descriptives.log
        tables: output/tables/baseline_table_*.csv
  # Self harm mortality graph
  create_selfharm_mortality:
    run: stata-mp:latest analysis/self_harm_graph.do  
    needs: []
    outputs:
      moderately_sensitive:
        log: logs/selfharm_mortgraph.log
        figures: output/tabfig/selfharm_mortgraph.svg


